/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModuloEstudiante;

import ModuloAsignacionEST.AsignarEstudiante;
import ModuloAsignacionEST.PrincipalAsignacionEST;
import java.sql.Connection;

/**
 *
 * @author Wilson Xicará
 */
public class PrincipalEstudiante extends javax.swing.JFrame {
    private Connection conexion;
    /**
     * Creates new form PrincipalEstudiante
     */
    public PrincipalEstudiante() {
        initComponents();
    }
    public PrincipalEstudiante(Connection conexion) {
        initComponents();
        this.conexion = conexion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crear_estudiante = new javax.swing.JButton();
        ver_estudiante = new javax.swing.JButton();
        asignar_estudiantes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Módulo Estudiante");

        crear_estudiante.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        crear_estudiante.setText("Crear Estudiante");
        crear_estudiante.setToolTipText("Permite crear un nuevo registro para un nuevo estudiante.\nTome en cuenta de que el programa le permitirá crear un nuevo estudiante siempre y cuando no tenga un Código Personal repetido con otro ya inscrito (el Código Personal es un atributo único para cada estudiante).");
        crear_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_estudianteActionPerformed(evt);
            }
        });

        ver_estudiante.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ver_estudiante.setText("Ver información de Estudiante");
        ver_estudiante.setToolTipText("Permite visualizar la información general de cada estudiante, así como poder editar dicha información y las notas asociadas al estudiante, en el Ciclo escolar vigente.");
        ver_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_estudianteActionPerformed(evt);
            }
        });

        asignar_estudiantes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        asignar_estudiantes.setText("Asignar Estudiantes");
        asignar_estudiantes.setToolTipText("Permite crear un nuevo registro para asignar un Estudiante a un Ciclo Escolar y a un Grado.\nEsta función es útil en caso de que a la hora de crear un nuevo estudiante no se crea la Asignación correspondiete (sólo mostrará el listado de los Estudiantes que aún no han sido asignados).");
        asignar_estudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignar_estudiantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ver_estudiante)
                        .addGap(185, 185, 185))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crear_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(asignar_estudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asignar_estudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ver_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crear_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_estudianteActionPerformed
        CrearEstudiante nueva_ventana = new CrearEstudiante(this, true, conexion);
        nueva_ventana.setVisible(true);
    }//GEN-LAST:event_crear_estudianteActionPerformed

    private void ver_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_estudianteActionPerformed
        InformacionEstudiante nueva_ventana = new InformacionEstudiante(this, true, conexion);
        nueva_ventana.setVisible(true);
    }//GEN-LAST:event_ver_estudianteActionPerformed

    private void asignar_estudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignar_estudiantesActionPerformed
        PrincipalAsignacionEST nueva_ventana = new PrincipalAsignacionEST(this, true, conexion);
        nueva_ventana.setVisible(true);
    }//GEN-LAST:event_asignar_estudiantesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignar_estudiantes;
    private javax.swing.JButton crear_estudiante;
    private javax.swing.JButton ver_estudiante;
    // End of variables declaration//GEN-END:variables
}
