/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Catedratico;

import Modulo_notas_y_reporte.Pantalla;
import java.awt.Frame;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.sql.Statement;
import java.util.logging.Logger;
import java.sql.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
/**
 *
 * @author oem
 */
public class ModuloPrincipalCatedratico extends javax.swing.JFrame {

    /**
     * Creates new form ModuloPrincipalCatedratico
     */
    Connection conexion;
    ResultSet respuesta;
    Statement stmt;
    
    String titulos [] = {"Nombre del curso",
                         "Grado",
                         "Seccion"};
    String fila[]= new String [3];
    DefaultTableModel modelo;
    int idcat, idcurso, idciclo;
    String Materia = "", A;
    ArrayList<String> Años;
    
    public ModuloPrincipalCatedratico() {
        initComponents();
    }
    
    public ModuloPrincipalCatedratico(Connection conex, ResultSet sentencia) throws SQLException{
        initComponents();
        conexion = conex;
        respuesta = sentencia;
        ResultSet rs2=null;
        Calendar fecha = new GregorianCalendar();
        A = Integer.toString(fecha.get(Calendar.YEAR));
        LlenarComboBoxx();
        Llenartabla();
    }
    public void LlenarComboBoxx() throws SQLException{
        boolean existe = false;
        Años = new ArrayList<String>();
        Statement stmt3 = conexion.createStatement();
        ResultSet consulta = stmt3.executeQuery("SELECT Id, anio FROM CicloEscolar ORDER BY anio");
        while(consulta.next()){
            String pivote = consulta.getString(2);
            Años.add(consulta.getString(1));
            if(pivote.equals(A)) existe = true;
            Campo_Año.addItem(pivote);
        }
        if(existe = true){
            Campo_Año.setSelectedItem(A);
        }
        
    }
    
    public void Llenartabla(){
        try{
           // int a = respuesta.getInt(5);
            Campo_Usuario.setText(respuesta.getString("NombreUsuario"));
            //Campo_Apellidos.setText(String.valueOf(respuesta.getInt(5)));
            idcat = respuesta.getInt(5);
            stmt = conexion.createStatement();
            String Opcion = Campo_Año.getSelectedItem().toString();
            
            ResultSet rs = stmt.executeQuery("SELECT curso.Nombre, grado.Nombre, grado.Seccion FROM asignacioncat "
                    + "INNER JOIN catedratico ON asignacioncat.Catedratico_Id = catedratico.Id " 
                    + "INNER JOIN curso ON asignacioncat.Curso_Id = curso.Id "
                    + "INNER JOIN cicloescolar ON asignacioncat.CicloEscolar_Id = cicloescolar.Id "
                    + "INNER JOIN grado ON asignacioncat.Grado_Id = grado.Id "
                    + "WHERE catedratico.id = "+idcat+" AND cicloescolar.anio = '"+ Opcion+ "'");
            modelo = new DefaultTableModel (null,titulos);
            //ResultSet rs = stmt.executeQuery("select* from curso");
            while(rs.next()){
                fila[0] = rs.getString("curso.Nombre");
                fila[1] = rs.getString("grado.Nombre");
                fila[2] = rs.getString("grado.Seccion");
                //fila[1] = rs.getString("catedratico.Nombres");
                modelo.addRow(fila);
            }
            Tabla.setModel(modelo);
            TableColumn ci = Tabla.getColumn("Nombre del curso");
            ci.setMaxWidth(500);
            TableColumn ci2 = Tabla.getColumn("Grado");
            ci2.setMaxWidth(100);
            TableColumn ci3 = Tabla.getColumn("Seccion");
            ci3.setMaxWidth(100);
            
        }catch (SQLException ex) {
            Logger.getLogger(ModuloPrincipalCatedratico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Campo_Usuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Campo_Año = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Campo_Usuario.setEditable(false);
        Campo_Usuario.setBackground(new java.awt.Color(204, 204, 204));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jLabel1.setText("Bienvenido:");

        Campo_Año.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Campo_AñoItemStateChanged(evt);
            }
        });

        jLabel2.setText("Año:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_Año, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Campo_Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Campo_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        
    }//GEN-LAST:event_TablaMouseClicked

    private void Campo_AñoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Campo_AñoItemStateChanged
        // TODO add your handling code here:
        if(Campo_Año.getSelectedIndex() != 1){
            int posicion = Campo_Año.getSelectedIndex();
            String p = Años.get(posicion);
            try{
           // int a = respuesta.getInt(5);
            Campo_Usuario.setText(respuesta.getString("NombreUsuario"));
            //Campo_Apellidos.setText(String.valueOf(respuesta.getInt(5)));
            idcat = respuesta.getInt(5);
            stmt = conexion.createStatement();
            String Opcion = Campo_Año.getSelectedItem().toString();
            
            ResultSet rs = stmt.executeQuery("SELECT curso.Nombre, grado.Nombre, grado.Seccion FROM asignacioncat "
                    + "INNER JOIN catedratico ON asignacioncat.Catedratico_Id = catedratico.Id " 
                    + "INNER JOIN curso ON asignacioncat.Curso_Id = curso.Id "
                    + "INNER JOIN cicloescolar ON asignacioncat.CicloEscolar_Id = cicloescolar.Id "
                    + "INNER JOIN grado ON asignacioncat.Grado_Id = grado.Id "
                    + "WHERE catedratico.id = "+idcat+" AND cicloescolar.anio = '"+ Opcion+ "'");
            modelo = new DefaultTableModel (null,titulos);
            //ResultSet rs = stmt.executeQuery("select* from curso");
            while(rs.next()){
                fila[0] = rs.getString("curso.Nombre");
                fila[1] = rs.getString("grado.Nombre");
                fila[2] = rs.getString("grado.Seccion");
                //fila[1] = rs.getString("catedratico.Nombres");
                modelo.addRow(fila);
            }
            Tabla.setModel(modelo);
            TableColumn ci = Tabla.getColumn("Nombre del curso");
            ci.setMaxWidth(500);
            TableColumn ci2 = Tabla.getColumn("Grado");
            ci2.setMaxWidth(100);
            TableColumn ci3 = Tabla.getColumn("Seccion");
            ci3.setMaxWidth(100);
            
            
        }catch (SQLException ex) {
            Logger.getLogger(ModuloPrincipalCatedratico.class.getName()).log(Level.SEVERE, null, ex);
        }
            //String 
        }
    }//GEN-LAST:event_Campo_AñoItemStateChanged

    private void TablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMousePressed
         try{
                if(evt.getClickCount() > 1){
            int fila = Tabla.getSelectedRow();
            
            Statement stmt2 = conexion.createStatement();
            String sql = "SELECT * FROM curso WHERE curso.Nombre = '"+Tabla.getValueAt(fila, 0).toString()+"'";
            ResultSet respuesta4 = stmt2.executeQuery(sql);
            int id=0;
            //System.out.println(id);
            while (respuesta4.next()){
                 id = respuesta4.getInt(1);
                 System.out.println(id); 
                 idcurso = id;
             }
            String sql2 = "SELECT cicloescolar.Id FROM cicloescolar WHERE cicloescolar.Anio = '"+Campo_Año.getSelectedItem().toString()+"'";
            ResultSet respuesta5 = stmt2.executeQuery(sql2);
            int id2=0;
            //System.out.println(id);
            while (respuesta5.next()){
                 id2 = respuesta5.getInt(1);
                 //System.out.println(id); 
                 idciclo = id2;
             }
            
            System.out.println(idcat);
            Pantalla s = new Pantalla(conexion,idcat, idcurso, idciclo, respuesta); // Llama a la del Andrés
            s.setVisible(true);
            this.dispose();
                }
        }catch (SQLException ex) {
            Logger.getLogger(ModuloPrincipalCatedratico.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_TablaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloPrincipalCatedratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloPrincipalCatedratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloPrincipalCatedratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloPrincipalCatedratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloPrincipalCatedratico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Campo_Año;
    private javax.swing.JTextField Campo_Usuario;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
