/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Catedratico;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author oem
 */
public class Mostrar_Datos extends javax.swing.JFrame {

    /**
     * Creates new form Mostrar_Datos
     */
    Connection conexion;
    Statement stmt;
    
    String titulos[] = {"ID","Nombres","Apellidos","Direccion"/*,"Telefono"*/,"DPI","Sexo","Etnia"/*,"Municipio"*/};
    String fila[] = new String [7];
    DefaultTableModel modelo;
    public Mostrar_Datos() {
        initComponents();
    }
    
    public Mostrar_Datos(Connection conex){
        initComponents();
        conexion = conex;
        try{
            stmt = conexion.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT* from catedratico");
            modelo = new DefaultTableModel(null,titulos);
            
            while(rs.next()) {
                   
                   fila[0] = rs.getString("ID");
                   fila[1] = rs.getString("Nombres");
                   fila[2] = rs.getString("Apellidos");
                   fila[3] = rs.getString("Direccion");
                   //fila[4] = rs.getString("Telefono");
                   fila[4] = rs.getString("DPI");
                   fila[5] = rs.getString("Sexo");
                   fila[6] = rs.getString("Etnia");
                   
                   modelo.addRow(fila);     
               }
            JTabla.setModel(modelo);
            TableColumn ci = JTabla.getColumn("ID");
                ci.setMaxWidth(25);
                TableColumn cn = JTabla.getColumn("Nombres");
                cn.setMaxWidth(145);
                TableColumn cd = JTabla.getColumn("Apellidos");
                cd.setMaxWidth(140);
                TableColumn ct = JTabla.getColumn("Direccion");
                ct.setMaxWidth(240);
              //  TableColumn cnick = Tabla.getColumn("Telefono");
              //  cnick.setMaxWidth(100);
                TableColumn cp = JTabla.getColumn("DPI");
                cp.setMaxWidth(85);
                TableColumn ctipo = JTabla.getColumn("Sexo");
                ctipo.setMaxWidth(50);
                TableColumn ca = JTabla.getColumn("Etnia");
                ca.setMaxWidth(75);

        }catch (SQLException ex) {
            Logger.getLogger(Mostrar_Datos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar_Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTabla;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
