/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Catedratico;


import Modulo_notas_y_reporte.Pantalla;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author oem
 */
public class Principal_catedratico extends javax.swing.JFrame {

    /**
     * Creates new form Principal_catedratico
     */
    String titulos [] = {"Nombre del curso"};
    String fila[]= new String [1];
    DefaultTableModel modelo;
    int idcat, idcurso;
    String Materia = "";
    
    Connection ab;
    Statement stmt;
    ResultSet respuesta;
    
    public Principal_catedratico(Connection p, ResultSet informacion){
        initComponents();
        respuesta = informacion;
        ab = p;
       // this.setTitle("Módulo cátedratico");
       // this.setLocation(335,220);
        try{
            int maestro;
            maestro = respuesta.getInt(5);
            System.out.println(maestro);
            idcat = maestro;
           // Campo_Usuario.setText(respuesta.getString("NombreUsuario"));
            Campo_Nombre.setText(respuesta.getString("Apellidos"));
            System.out.println(maestro);
            
           
            ResultSet rs = stmt.executeQuery("SELECT curso.Nombre, catedratico.Nombres FROM asignacioncat INNER JOIN catedratico ON asignacioncat.Catedratico_Id = catedratico.Id " +
            "INNER JOIN curso ON asignacioncat.Curso_Id = curso.Id WHERE catedratico.Id = "+maestro);
            modelo = new DefaultTableModel (null,titulos);
            //ResultSet rs = stmt.executeQuery("select* from curso");
            while(rs.next()){
                fila[0] = rs.getString("curso.Nombre");
                //fila[1] = rs.getString("catedratico.Nombres");
                modelo.addRow(fila);
            }
            Tabla.setModel(modelo);
            TableColumn ci = Tabla.getColumn("Nombre del curso");
            ci.setMaxWidth(700);
            TableColumn cn = Tabla.getColumn("catedratico.Nombres");
            cn.setMaxWidth(500);
           
           
           
            
        }
        catch (SQLException ex) {
            Logger.getLogger(Principal_catedratico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public Principal_catedratico() {
        initComponents();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Campo_Curso = new javax.swing.JTextField();
        Campo_Usuario = new javax.swing.JTextField();
        Campo_Nombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 73, 381, 173));

        jLabel1.setText("Bienvenido:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel2.setText("Año:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        Campo_Curso.setEditable(false);
        Campo_Curso.setBackground(new java.awt.Color(204, 204, 204));
        Campo_Curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_CursoActionPerformed(evt);
            }
        });
        getContentPane().add(Campo_Curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 130, 30));

        Campo_Usuario.setEditable(false);
        Campo_Usuario.setBackground(new java.awt.Color(51, 255, 0));
        Campo_Usuario.setText(" ");
        Campo_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Campo_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 110, -1));

        Campo_Nombre.setText("jTextField1");
        getContentPane().add(Campo_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Pantalla s= new Pantalla(); 
        
        try{
            int maestro = 0;
            //System.out.println(maestro);
/**            String url = "jdbc:mysql://localhost:3306/sbd_inebxela";
            String usuario = "root";
            String contraseña = "6148";  
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            ab = DriverManager.getConnection(url,usuario,contraseña);**/
          stmt = ab.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY); 
           String sql = "SELECT * FROM curso WHERE curso.Nombre = '"+Materia+"'";
           ResultSet respuesta4 = stmt.executeQuery(sql);
           int id=0;
           //System.out.println(id);
           while (respuesta4.next()){
                id = respuesta4.getInt(1);
                //System.out.println(id);
                idcurso = id;
            }
           Pantalla s = new Pantalla(ab,idcat, idcurso, respuesta); // Llama a la del Andrés
           s.setVisible(true);
           this.dispose();
           
          // System.out.println(idcurso+ " "+idcat);
    }
           catch (SQLException ex) {
            Logger.getLogger(Principal_catedratico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Campo_CursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_CursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_CursoActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
           int fila = Tabla.getSelectedRow();
           int columna = Tabla.getSelectedColumn();
           
           String curso= Tabla.getValueAt(fila, columna).toString();
           //System.out.println(curso);
           Campo_Curso.setText(curso);
           Materia = curso;
    }//GEN-LAST:event_TablaMouseClicked

    private void Campo_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_catedratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_catedratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_catedratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_catedratico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_catedratico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Campo_Curso;
    private javax.swing.JTextField Campo_Nombre;
    private javax.swing.JTextField Campo_Usuario;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
