/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModuloAsignacionEST;

import ModuloEstudiante.InformacionEstudiante;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Clase que permite crear UNA ASIGNACIÓN PARA UN ESTUDIANTE. Para ello, se evalua si la Asignación ya existe (que exista un
 * registro de Asignación correspondiente al Ciclo Escolar en curso).
 * @author Wilson Xicará
 */
public class AsignarEstudiante extends javax.swing.JDialog {
    private Connection conexion;
    private ResultSet consultaCicloEscolar, consultaGrado = null;
    private Statement sentencia;
    private DefaultTableModel tablaModelEst, tablaModelCursos;
    private int estudiante_Id, cicloEscolar_Id, grado_Id;
    private boolean ciclosCargados = false, gradosCargados = false;
    /**
     * Creates new form AsignacionEST
     */
    public AsignarEstudiante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public AsignarEstudiante(java.awt.Frame parent, boolean modal, Connection conexion, int estudiante_Id) {
        super(parent, modal);
        initComponents();
        /* Extraigo parte de la información del estudiante para mostrarlo. */
        this.conexion = conexion;
        try {
            this.sentencia = this.conexion.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
        } catch (SQLException ex) {
            Logger.getLogger(AsignarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.estudiante_Id = estudiante_Id;
        iniciarTabla();
        extraerDatosEstudiante();
        extraerDatosAsignacion();
        tabla_info_estudiante.setModel(tablaModelEst);
    }
    private void iniciarTabla() {
        // Definición de las columnas de 'tablaModelEst'
        tablaModelEst = new DefaultTableModel();
        tablaModelEst.addColumn("Código Personal");
        tablaModelEst.addColumn("CUI");
        tablaModelEst.addColumn("Nombre Completo");
    }
    private void extraerDatosEstudiante() {
        try {
            // Extraigo el registro del Estudiante con Id 'estudiante_Id' (ya existe y es único).
            ResultSet consulta = sentencia.executeQuery("SELECT CodigoPersonal, CUI, Nombres, Apellidos, Sexo FROM Estudiante WHERE Id = "+estudiante_Id);
            // Inicio la extracción de datos
            consulta.next();
            String[] registro = {
                consulta.getString("CodigoPersonal"),
                consulta.getString("CUI"),
                consulta.getString("Nombres")+" "+consulta.getString("Apellidos")
            };
            tablaModelEst.addRow(registro);
            String titulo = "Asignación ";
            titulo+= (consulta.getString("Sexo").equals("F"))?"de la":"del";
            titulo+= " estudiante "+consulta.getString("Nombres")+" "+consulta.getString("Apellidos");
            this.setTitle(titulo);
        } catch (SQLException ex) {
            Logger.getLogger(InformacionEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void extraerDatosAsignacion() {
        try {
            ciclo_escolar.removeAllItems();
            // Realizo una consulta a la tabla CicloEscolar
            Statement sentencia = conexion.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
            consultaCicloEscolar = sentencia.executeQuery("SELECT * FROM CicloEscolar");
            // Cargo los datos de la consulta al JComboBox
//            ciclo_escolar.addItem(consultaCicloEscolar.getString("Anio"));
            while(consultaCicloEscolar.next()) {
                ciclo_escolar.addItem(consultaCicloEscolar.getString("Anio"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AsignarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_info_estudiante = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ciclo_escolar = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        grado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        crear_asignacion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        aula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_info_cursos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignación de Estudiantes");

        tabla_info_estudiante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabla_info_estudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_info_estudiante);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Información del(la) estudiante:");

        ciclo_escolar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ciclo_escolar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ciclo_escolarItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ciclo escolar:");

        grado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        grado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gradoItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Grado:");

        crear_asignacion.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        crear_asignacion.setText("Crear Asignación");
        crear_asignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_asignacionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Aula:");

        aula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cursos:");

        tabla_info_cursos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabla_info_cursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla_info_cursos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(ciclo_escolar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(crear_asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ciclo_escolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(crear_asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ciclo_escolarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ciclo_escolarItemStateChanged
        // Realizo una consulta a las tablas AsignacionCAT y Grado para buscar todos los grados del Ciclo Escolar en curso
        int itemSeleccionado = ciclo_escolar.getSelectedIndex();
        if (itemSeleccionado > -1) {
            grado.removeAllItems();
            try {
                Statement sentencia = conexion.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
                consultaCicloEscolar.first();   // Regreso al primer registro de la columna
                for(int i=1; i<=itemSeleccionado; i++) consultaCicloEscolar.next();
                cicloEscolar_Id = consultaCicloEscolar.getInt("Id");
                // Realizo la consulta a las tablas AsignacionCAT y Grado: los Grados que tiene asignado el Ciclo Escolar seleccionado
                consultaGrado = sentencia.executeQuery("SELECT AsignacionCAT.CicloEscolar_Id, AsignacionCAT.Grado_Id, Grado.*, COUNT(AsignacionCAT.Grado_Id) FROM AsignacionCAT "
                        + "INNER JOIN Grado ON AsignacionCAT.Grado_Id = Grado.Id "
                        + "WHERE AsignacionCAT.CicloEscolar_Id = "+cicloEscolar_Id+" "
                        + "GROUP BY AsignacionCAT.Grado_Id");
                // Cargo los datos al JComboBox correspondiente
                while(consultaGrado.next()) {
                    grado.addItem(consultaGrado.getString("Nombre")+" "+consultaGrado.getString("Seccion"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(AsignarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ciclo_escolarItemStateChanged

    private void crear_asignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_asignacionActionPerformed
        /* Para la asignación, el Ciclo Escolar se obtiene de 'ciclo_escolar.getSelectedIndex()' y el Grado se obtiene de
            'grado.getSelectedIndex()'. Para ambos casos, sólo obtengo el Índice dentro de los JComboBox, pero puedo averiguar
            a qué registro de la consulta pertenece (ya que el contenido de los ComboBox se obtiene del último valor de ambas
            consultas). Obtengo los Índices de los JComboBox y busco los Id's correspondientes en las consultas */
        try {
            ResultSet consulta;
            // Tengo el Ciclo Escolar en 'this.cicloEscolar_Id'
            // Tengo el Grado en 'this.grado_Id'
            
            /* Creación de la Asignación del Nuevo Estudiante */
            // Obtengo el Id de la nueva Asignación:
            consulta = sentencia.executeQuery("SELECT COUNT(*) Cantidad FROM AsignacionEST");
            consulta.next();
            int asignacionEST_Id = consulta.getInt("Cantidad") + 1;
            
            String nuevaAsignacion = "INSERT INTO AsignacionEst(CicloEscolar_Id, Grado_Id, Estudiante_Id, Aula) VALUES("
                    + cicloEscolar_Id + "," + grado_Id + "," + estudiante_Id + ",'" + aula.getText() + "')";
            conexion.prepareStatement(nuevaAsignacion).executeUpdate(); // Inserto y actulizo
            asignarCursos(asignacionEST_Id);
            
            JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Se creó la asignación y los cursos con éxito!", "Insertado", JOptionPane.INFORMATION_MESSAGE);
            crear_asignacion.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(AsignarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_crear_asignacionActionPerformed

    private void gradoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gradoItemStateChanged
        // Realizo una consulta a las Tablas Grado, AsignacionCAT y Cursos para mostrar todos los cursos del Grado y Ciclo Escolar en curso
        int itemSeleccionado = grado.getSelectedIndex();
        if (itemSeleccionado > -1) {
            // Definición de las columnas de 'tablaModelCursos'
            tablaModelCursos = new DefaultTableModel();
            tablaModelCursos.addColumn("Cursos");
            try {
                consultaGrado.first();  // Regreso al primer registro de la consulta
                for(int i=1; i<=itemSeleccionado; i++) consultaGrado.next();
                grado_Id = consultaGrado.getInt("Grado_Id");
                // Obtengo los cursos asignados al Ciclo Escolar y Grado correspondientes
                ResultSet cursos = sentencia.executeQuery("SELECT CicloEscolar_Id, Grado_Id, Curso_Id, Curso.Nombre FROM AsignacionCAT "
                        + "INNER JOIN Curso ON AsignacionCAT.Curso_Id = Curso.Id "
                        + "WHERE AsignacionCAT.CicloEscolar_Id = "+cicloEscolar_Id+" AND Grado_Id = "+grado_Id+"");
                while (cursos.next())
                    tablaModelCursos.addRow(new String[]{cursos.getString("Nombre")});
                tabla_info_cursos.setModel(tablaModelCursos);
            } catch (SQLException ex) {
                Logger.getLogger(AsignarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_gradoItemStateChanged
    private void asignarCursos(int asignacionEST_Id) {
        String nuevasNotas = "";
        /* Obtengo los Cursos que se le asignarán al Estudiante, y se los asigno al crear Notas */
        try {
            String nuevosCursos = "SELECT CicloEscolar.Id CicloEscolar_Id, CicloEscolar.Anio, Grado.Id Grado_Id, Grado.Nombre Grado, Curso.Id Curso_Id, Curso.Nombre Curso FROM CicloEscolar "
                    + "INNER JOIN AsignacionCAT ON CicloEscolar.Id = AsignacionCAT.CicloEscolar_Id "
                    + "INNER JOIN Grado ON AsignacionCAT.Grado_Id = Grado.Id "
                    + "INNER JOIN Curso ON AsignacionCAT.Curso_Id = Curso.Id "
                    + "WHERE CicloEscolar_Id = "+cicloEscolar_Id+" AND Grado_Id = "+grado_Id+"";
            ResultSet consulta = sentencia.executeQuery(nuevosCursos);  // Realizo la consulta
            
            nuevasNotas+= "INSERT INTO Notas(AsignacionEST_Id, Estudiante_Id, Curso_Id, Nota1, Nota2, Nota3, Nota4, NotaRecuperacion, NotaFinal) VALUES";
            
            // Inicio la extracción de los Cursos que se asignarán
            while(consulta.next()) {
                nuevasNotas+= "("+asignacionEST_Id+","+estudiante_Id+","+consulta.getInt("Curso_Id")+",0,0,0,0,0,0),";
            } nuevasNotas = nuevasNotas.substring(0, nuevasNotas.length()-1);
            conexion.prepareStatement(nuevasNotas).executeUpdate();    // Inserto y actulizo
        } catch (SQLException ex) {
            Logger.getLogger(AsignarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AsignarEstudiante dialog = new AsignarEstudiante(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aula;
    private javax.swing.JComboBox<String> ciclo_escolar;
    private javax.swing.JButton crear_asignacion;
    private javax.swing.JComboBox<String> grado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_info_cursos;
    private javax.swing.JTable tabla_info_estudiante;
    // End of variables declaration//GEN-END:variables
}
