/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModuloAsignacionEST;

import ModuloEstudiante.InformacionEstudiante;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 * Clase que permite crear VARIAS ASIGNACIONES PARA VARIOS ESTUDIANTE. Para ello, se evalua si la Asignación ya existe (que
 * exista un registro de Asignación correspondiente al Ciclo Escolar en curso). Carga los datos de los Estudiantes que no
 * tienen una Asignación.
 * @author Wilson Xicará
 */
public class PrincipalAsignacionEST extends javax.swing.JDialog {
    private Connection conexion;
    private ResultSet consultaAsignaciones;
    private DefaultTableModel tablaModel;
    /**
     * Creates new form AsignacionEST
     */
    public PrincipalAsignacionEST(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public PrincipalAsignacionEST(java.awt.Frame parent, boolean modal, Connection conexion) {
        super(parent, modal);
        initComponents();
        this.conexion = conexion;
        this.consultaAsignaciones = null;
        mostrarEstudiantesNoAsignados();
    }
    private void iniciarTabla() {
        tablaModel = new DefaultTableModel();
        // Definición de las columnas de 'tablaModel'
        tablaModel.addColumn("No.");
        tablaModel.addColumn("Código Personal");
        tablaModel.addColumn("CUI");
        tablaModel.addColumn("Nombres");
        tablaModel.addColumn("Apellidos");
        tablaModel.addColumn("Asignado");
        tabla_estudiantes.setModel(tablaModel);
    }
    private void mostrarEstudiantesNoAsignados() {
        iniciarTabla();
        try {
            /* Obtengo la consulta de todos los Estudiantes que aún no tienen una Asignación */
            Statement sentencia = conexion.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
            consultaAsignaciones = sentencia.executeQuery("SELECT Estudiante.Id, Estudiante.CodigoPersonal, Estudiante.CUI, Estudiante.Nombres, Estudiante.Apellidos, AsignacionEST.* FROM Estudiante "
                    + "LEFT JOIN AsignacionEST ON Estudiante.Id = AsignacionEST.Estudiante_Id "
                    + "WHERE AsignacionEst.Id IS NULL");
            int contador = 1;
            // Obtención e inserción de las filas en 'tabla'
            while (consultaAsignaciones.next()) {
                String[] registro = {
                    Integer.toString(contador),
                    consultaAsignaciones.getString("CodigoPersonal"),
                    consultaAsignaciones.getString("CUI"),
                    consultaAsignaciones.getString("Nombres"),
                    consultaAsignaciones.getString("Apellidos"),
                    "NO"
                };
                tablaModel.addRow(registro); // Inserción del i-ésimo registro en la tabla
                contador++;
            }
            jLabel1.setText("Estudiantes que aún no han sido asignados: "+tablaModel.getRowCount()+" registro(s).");
//            consultaEstudiante.close();   // No cierro la consulta pues me servirá para modificar algún registro
        } catch (SQLException ex) {
            Logger.getLogger(InformacionEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_estudiantes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignación de Estudiantes");
        setLocation(new java.awt.Point(100, 10));

        tabla_estudiantes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabla_estudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_estudiantes);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Crear Asignación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Estudiantes que aún no han sido asignados:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int filaSeleccionada = tabla_estudiantes.getSelectedRow();
        if (filaSeleccionada != -1) {
            try {
                // Obtengo el Id del estudiante al que se le creará su Asignación
                consultaAsignaciones.first();   // Me desplazo hasta el primer registro de la consulta
                for(int i=0; i<filaSeleccionada; i++) consultaAsignaciones.next();
                int estudiante_Id = consultaAsignaciones.getInt("Id");  // Obtengo el Id del estudiante seleccionado
                // Llamo a la Ventana encargada de realizar la Asignación
                AsignarEstudiante nuevaAsignacion = new AsignarEstudiante(new javax.swing.JFrame(), true, conexion, estudiante_Id);
                nuevaAsignacion.setVisible(true);
                mostrarEstudiantesNoAsignados();    // Actualizo los datos (con los Estudiantes no Asignados)
            } catch (SQLException ex) {
                Logger.getLogger(PrincipalAsignacionEST.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAsignacionEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAsignacionEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAsignacionEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAsignacionEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PrincipalAsignacionEST dialog = new PrincipalAsignacionEST(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_estudiantes;
    // End of variables declaration//GEN-END:variables
}
