/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModuloPrestamos;

import ModuloAdministrador.ModuloPrincipalAdmin;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SERGIO
 */
public class ModuloPrestamo extends javax.swing.JFrame {

    /**
     * Creates new form ModuloPrestamo
     */
    Connection conexcion;
    DefaultTableModel modelo;
    DefaultTableModel modelo2;
    ResultSet Packs = null;
    ResultSet Alumnos = null;
    ResultSet Ciclos = null;
    JFrame Ventanita;
    int vId = 0;
    public ModuloPrestamo() {
        initComponents();
    }
    
    public ModuloPrestamo(Connection conec,JFrame ventana){
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            modelo = (DefaultTableModel) Paquetes.getModel();
            modelo2 = (DefaultTableModel) Estudiantes.getModel();
            conexcion = conec;
            Ventanita = ventana;
            //agregar al combobox los ciclos
            Statement senten = conexcion.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
            Ciclos = senten.executeQuery("SELECT * FROM cicloescolar;");
            if(Ciclos.next()!=false){
                Ciclos.previous();
                while(Ciclos.next()!=false){
                    Ciclo.addItem(Ciclos.getString(2));
                }
                Ciclos.first();
            }
            else{
                JOptionPane.showMessageDialog(null, "¡No existen Ciclos Escolares Creados!");
            }
            //revisar eso y la funcion si sirven
            DatosPaquetes();
            //DatosEst();
        } catch (SQLException ex) {
            Logger.getLogger(ModuloPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NoFactura = new javax.swing.JTextField();
        CodigoPaquete = new javax.swing.JTextField();
        Monto = new javax.swing.JTextField();
        CodigoEstudiante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Paquetes = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Estudiantes = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        Ciclo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1316, 713));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prestamo de Libros");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 1320, 22);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1220, 1022, 0, 0);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Prestamo");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 440, 115, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 440, 115, 25);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Listado de Prestamos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(470, 620, 202, 34);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Listado Paquetes");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(250, 620, 202, 34);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1208, 1022, 0, 0);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1220, 1029, 0, 0);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1199, 616, 0, 0);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1206, 227, 0, 0);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Regresar Menú Principal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(60, 620, 177, 34);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Prestamo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("No.Factura");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Codigo del Paquete");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Monto (Q)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Codigo Estudiante");

        NoFactura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NoFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NoFacturaKeyTyped(evt);
            }
        });

        CodigoPaquete.setEditable(false);
        CodigoPaquete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Monto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        CodigoEstudiante.setEditable(false);
        CodigoEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(92, 92, 92)
                                .addComponent(NoFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CodigoPaquete)
                                    .addComponent(Monto)
                                    .addComponent(CodigoEstudiante))))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(NoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(CodigoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CodigoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(430, 170, 410, 247);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1213, 981, 0, 0);

        Paquetes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Paquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Codigo Paquete", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(Paquetes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 150, 380, 378);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Seleccionar Paquete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(130, 540, 155, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Paquetes Disponibles");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 120, 127, 17);

        Estudiantes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Estudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombres", "Apellidos"
            }
        ));
        jScrollPane2.setViewportView(Estudiantes);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(880, 160, 410, 370);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Estudiantes Disponibles");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(880, 130, 150, 17);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton1.setText("Seleccionar Estudiante");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(1030, 540, 169, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ciclo Escolar");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 70, 80, 17);

        Ciclo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CicloActionPerformed(evt);
            }
        });
        getContentPane().add(Ciclo);
        Ciclo.setBounds(130, 70, 130, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new ListadoPaquetes(conexcion).setVisible(true);                    //Despliega la ventana ListadoPaquetes
        this.setEnabled(true);
        //Cerrar o minimizar ventana ModuloPrestamos
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new ListadoPrestamos(conexcion).setVisible(true);                   //Despliega la ventana ListadoPrestamos
        this.setEnabled(true);
        //Cerrar o minimizar ventana ModuloPrestamos
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        NoFactura.setText("");
        CodigoPaquete.setText("");
        CodigoEstudiante.setText("");
        Monto.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String NoFac, CodPack, CodEst,Instruccion = "";
        float Efectivo;
        ResultSet resultado = null, resultado2 = null, prest = null;
        if(CodigoPaquete.getText().equals("") == true){
            JOptionPane.showMessageDialog(null, "¡No ha seleccionado ningun paquete!");
        }
        else if(CodigoEstudiante.getText().equals("") == true){
            JOptionPane.showMessageDialog(null, "¡No ha seleccionado ningun Estudiante!");
        }
        else if((NoFactura.getText().equals(""))||(Monto.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "¡Hay Campos Vacios!");
        }
        else{
            NoFac = NoFactura.getText();
            CodPack = CodigoPaquete.getText();
            CodEst = CodigoEstudiante.getText();
            Efectivo = Float.parseFloat(Monto.getText());
            //Condicion que si el CodigoEstudiante no existe en la base arrojar un mensaje
            //Condicion si el CodigoPaquete no existe
            try {Statement sentencia = conexcion.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
                resultado = sentencia.executeQuery("SELECT * FROM paquetelibro WHERE Codigo = '" + CodPack + "';");
                Statement sentencia2 = conexcion.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
                resultado2 = sentencia2.executeQuery("SELECT * FROM estudiante WHERE CodigoPersonal = " + "'" + CodEst + "';");
                Statement sentencia3 = conexcion.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
                prest = sentencia3.executeQuery("SELECT * FROM prestamo WHERE prestamo.PaqueteLibro_Id = '" + CodPack + "';");
                //Condicion que si el CodigoEstudiante no existe en la base arrojar un mensaje
                //Condicion si el No Factura ya existe
                if(prest.next() == true){
                    JOptionPane.showMessageDialog(null, "Ya Existe un prestamo con ese paquete");
                }
                else{
                    //Concatenamos la instrucción para insertar a la tabla prestamo.
                    //System.out.println(resultado.next());
                    //System.out.println(resultado2.next());
                    resultado.next();
                    resultado2.next();
                    Instruccion = "INSERT INTO prestamo(PaqueteLibro_ID,Estudiante_ID,CodigoBoleta,FechaPago,Monto) VALUES (" + resultado.getString(1) + "," + resultado2.getString(1) +  "," + "'" + NoFac + "'" + ",NOW()," + Efectivo + ");"; //Insercion a la Tabla Prestamos
                     //Insertamos en la base
                    try {
                        PreparedStatement  pst = conexcion.prepareStatement(Instruccion);
                        int a = pst.executeUpdate();
                        pst.close();
                        if (a>0){
                            int filas = Paquetes.getRowCount();
                            int filas2 = Estudiantes.getRowCount();
                            for (int i = 0;i<filas; i++) {
                                modelo.removeRow(0);
                            }
                            for(int j = 0;j<filas2;j++){
                                modelo2.removeRow(0);
                            }
                            System.out.println("Guardado");
                            JOptionPane.showMessageDialog(null, "¡Se ha compleado el Prestamo del libro " + CodPack + " Exitosamente!");
                            DatosPaquetes(); //revisar la funcion
                            //modelo2.setRowCount(0);
                            if(Ciclo.getSelectedIndex()!=-1){
                                DatosEst(Ciclos.getString(2));
                            }
                            NoFactura.setText("");
                            CodigoPaquete.setText("");
                            CodigoEstudiante.setText("");
                            Monto.setText("");
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(ModuloPrestamo.class.getName()).log(Level.SEVERE, null, ex);
                        System.out.println("Error en SQLException: "+ex.getMessage());
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Ventanita.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String vCodigo = "",vDescrip;
        if(Paquetes.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila");
        }
        else{
            vCodigo = Paquetes.getValueAt(Paquetes.getSelectedRow(), 1).toString();
            CodigoPaquete.setText(vCodigo);
            vId = Integer.parseInt(Paquetes.getValueAt(Paquetes.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Ventanita.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        String vCodigo = "",vDescrip;
        if(Estudiantes.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila");
        }
        else{
            vCodigo = Estudiantes.getValueAt(Estudiantes.getSelectedRow(), 0).toString();
            CodigoEstudiante.setText(vCodigo);
            //vId = Integer.parseInt(Paquetes.getValueAt(Paquetes.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void CicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CicloActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        if(Ciclo.getSelectedIndex() != -1){
            try {
                modelo2.setRowCount(0);
                cont = Ciclo.getSelectedIndex();
                Ciclos.first();
                for(int conta = 0; conta < cont; conta++){
                    try {
                        Ciclos.next();
                    } catch (SQLException ex) {
                        Logger.getLogger(ModuloPrestamo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                DatosEst(Ciclos.getString(2));
            } catch (SQLException ex) {
                Logger.getLogger(ModuloPrestamo.class.getName()).log(Level.SEVERE, null, ex);
            }
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_CicloActionPerformed

    private void NoFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoFacturaKeyTyped
        // TODO add your handling code here:
        if(NoFactura.getText().length()==5){
            evt.consume();
        }
    }//GEN-LAST:event_NoFacturaKeyTyped
    public void DatosPaquetes(){
        int cont = 1;
        try {
            Statement sentencia = conexcion.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
            
            //revisar la consulta
            Packs = sentencia.executeQuery("SELECT L.Id,L.Codigo,L.Descripcion FROM prestamo P RIGHT JOIN paquetelibro L ON P.PaqueteLibro_Id = L.Id WHERE P.PaqueteLibro_Id is null;");
            if(Packs.next() == false){
                //No hay paquetes disponibles
            }
            else{
                Packs.previous();
                while(Packs.next() != false){
                    modelo.addRow(new Object[]{cont,Packs.getString(2),Packs.getString(3)});
                    cont++;
                }
            }
        } catch (SQLException e) {
                e.printStackTrace();
        }
    }
    public void DatosEst(String ciclito){
        try {
            Statement sentencia2 = conexcion.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
            Alumnos = sentencia2.executeQuery("SELECT E.CodigoPersonal, E.Nombres, E.Apellidos FROM cicloescolar C INNER JOIN asignacionest A ON  C.Id = A.CicloEscolar_Id\n" +
            "INNER JOIN estudiante E ON A.Estudiante_Id=E.Id LEFT JOIN prestamo P ON E.Id = P.Estudiante_Id WHERE P.Estudiante_Id is null AND C.Anio = '" + ciclito + "';");
            //Alumnos = sentencia2.executeQuery("SELECT A.CodigoPersonal, A.Nombres, A.Apellidos FROM estudiante A LEFT JOIN prestamo P ON A.Id = P.Estudiante_Id WHERE P.Estudiante_Id is null;");
            if(Alumnos.next()==false){
                
            }
            else{
                Alumnos.previous();
                while(Alumnos.next() != false){
                    modelo2.addRow(new Object[]{Alumnos.getString(1),Alumnos.getString(2),Alumnos.getString(3)});
                    //cont++;
                }
            }
        } catch (SQLException e) {
                e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Ciclo;
    private javax.swing.JTextField CodigoEstudiante;
    private javax.swing.JTextField CodigoPaquete;
    private javax.swing.JTable Estudiantes;
    private javax.swing.JTextField Monto;
    private javax.swing.JTextField NoFactura;
    private javax.swing.JTable Paquetes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
